### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by rahulkrvnit** [mathebox/django_hana_pyhdb#1]
Hi contributors

I am using Django with HANA and I am getting following error
AttributeError: 'SQLInsertCompiler' object has no attribute 'placeholder'
Django = 1.9 and HANA = SPS11
Is this version issue or any bug?

regards
Rahul

**Comment by mathebox** [comment]
Hi Rahul,

Yes this seems to be an error caused by Django 1.9.
In our project we still use Django 1.8 to avoid these kind of errors. Please be also aware that there might be some feature missing and the code is not tested.

I'm willing to put some effort in supporting more Django and Python versions. But therefore automated tests have to be set up. Here the problem is to establish to connection from the CI server (e.g. Travis) to a HANA database. This can be managed by using the HANA Cloud Platform. But a trial account is not sufficient because the account is going to be disabled after too many database requests. 

However, if you are willing to contribute, pull requests are more than welcome.

**Comment by rahulkrvnit** [comment]
Hi Mathebox,
 Thanks a lot for your info. I would love to contribute to the open source like this.
could you please share some info, what all technologies I have to acquire in order to contribute? Sources for those would be very helpful. I have initial knowledge of HANA,Python and Django
Regards
Rahul
